using Nop.Core;

namespace ARM.Logistics.Payments.Square
{
    /// <summary>
    /// Represents plugin constants
    /// </summary>
    public class SquarePaymentDefaults
    {
        /// <summary>
        /// Square payment method system name
        /// </summary>
        public static string SystemName => "Logistics.Payments.Square";

        /// <summary>
        /// Square payment method currency code
        /// </summary>
        public static string CurrencyCode => "USD";

        /// <summary>
        /// User agent used to request Square services
        /// </summary>
        public static string UserAgent => $"ARM-{NopVersion.CURRENT_VERSION}";

        /// <summary>
        /// The Integration ID should be added in the charge endpoint in order to correctly track the profit generated by the merchants using the Square payment plugin
        /// </summary>
        public static string IntegrationId => "sqi_4efb0346e2ef4b1375319dcd6e9977c0";

        /// <summary>
        /// One page checkout route name
        /// </summary>
        public static string OnePageCheckoutRouteName => "CheckoutOnePage";

        /// <summary>
        /// Path to the Square payment form js script
        /// </summary>
        public static string PaymentFormScriptPath => "https://web.squarecdn.com/v1/square.js";

        /// <summary>
        /// Path to the Square payment form js script
        /// </summary>
        public static string SandboxPaymentFormScriptPath => "https://sandbox.web.squarecdn.com/v1/square.js";

        /// <summary>
        /// Key of the attribute to store Square customer identifier
        /// </summary>
        public static string CustomerIdAttribute => "SquareCustomerId";

        /// <summary>
        /// Name of the route to the access token callback
        /// </summary>
        public static string AccessTokenRoute => "Plugin.Payments.Square.AccessToken";

        /// <summary>
        /// Name of the renew access token schedule task
        /// </summary>
        public static (string Name, string Type, int Period, int MaxPeriod) RenewAccessTokenTask =>
            ("Renew access token (Square payment)", "ARM.Logistics.Payments.Square.Services.RenewAccessTokenTask", 5, 30);

        /// <summary>
        /// Sandbox credentials should start with this prefix
        /// </summary>
        public static string SandboxCredentialsPrefix => "sandbox-";

        /// <summary>
        /// Note passed for each payment transaction
        /// </summary>
        /// <remarks>
        /// {0} : Order Guid
        /// </remarks>
        public static string PaymentNote => "ARM: {0}";

        /// <summary>
        /// Date time format
        /// </summary>
        public static string DateTimeFormat => "yyyy-MM-dd";

        public class Status
        {
            /// <summary>
            /// Payment status "APPROVED"
            /// </summary>
            public const string PAYMENT_APPROVED = "APPROVED";

            /// <summary>
            /// Payment status "COMPLETED"
            /// </summary>
            public const string PAYMENT_COMPLETED = "COMPLETED";

            /// <summary>
            /// Payment status "FAILED"
            /// </summary>
            public const string PAYMENT_FAILED = "FAILED";

            /// <summary>
            /// Payment status "CANCELED"
            /// </summary>
            public const string PAYMENT_CANCELED = "CANCELED";

            /// <summary>
            /// Location status "ACTIVE"
            /// </summary>
            public const string LOCATION_ACTIVE = "ACTIVE";

            /// <summary>
            /// Location capability "CREDIT_CARD_PROCESSING"
            /// </summary>
            public const string LOCATION_PROCESSING = "CREDIT_CARD_PROCESSING";

            /// <summary>
            /// Refund status "PENDING"
            /// </summary>
            public const string REFUND_PENDING = "PENDING";

            /// <summary>
            /// Refund status "COMPLETED"
            /// </summary>
            public const string REFUND_COMPLETED = "COMPLETED";
        }

        public class Invoice
        {
            /// <summary>
            /// Invoice delivery method "EMAIL"
            /// </summary>
            public const string TITLE = "Vehicle Shipping";

            /// <summary>
            /// Invoice delivery method "EMAIL"
            /// </summary>
            public const string DELIVERY_METHOD_EMAIL = "EMAIL";

            /// <summary>
            /// Invoice request type "BALANCE"
            /// </summary>
            public const string REQUEST_TYPE_BALANCE = "BALANCE";

            /// <summary>
            /// Invoice status "DRAFT"
            /// </summary>
            public const string STATUS_DRAFT = "DRAFT";

            /// <summary>
            /// Invoice status "UNPAID"
            /// </summary>
            public const string STATUS_UNPAID = "UNPAID";

            /// <summary>
            /// Invoice status "SCHEDULED"
            /// </summary>
            public const string STATUS_SCHEDULED = "SCHEDULED";

            /// <summary>
            /// Invoice status "PARTIALLY_PAID"
            /// </summary>
            public const string STATUS_PARTIALLY_PAID = "PARTIALLY_PAID";

            /// <summary>
            /// Invoice status "PAID"
            /// </summary>
            public const string STATUS_PAID = "PAID";

            /// <summary>
            /// Invoice status "PARTIALLY_REFUNDED"
            /// </summary>
            public const string STATUS_PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED";

            /// <summary>
            /// Invoice status "REFUNDED"
            /// </summary>
            public const string STATUS_REFUNDED = "REFUNDED";

            /// <summary>
            /// Invoice status "CANCELED"
            /// </summary>
            public const string STATUS_CANCELED = "CANCELED";

            /// <summary>
            /// Invoice status "FAILED"
            /// </summary>
            public const string STATUS_FAILED = "FAILED";

            /// <summary>
            /// Invoice status "PAYMENT_PENDING"
            /// </summary>
            public const string STATUS_PAYMENT_PENDING = "PAYMENT_PENDING";
        }

        public class Order
        {
            /// <summary>
            /// Order item type "ITEM"
            /// </summary>
            public const string ITEM_TYPE_ITEM = "ITEM";

            /// <summary>
            /// Order state "OPEN"
            /// </summary>
            public const string STATE_OPEN = "OPEN";

            /// <summary>
            /// Order state "CANCELED"
            /// </summary>
            public const string STATE_CANCELED = "CANCELED";

            /// <summary>
            /// Order service charge calculation phase "SUBTOTAL_PHASE"
            /// </summary>
            public const string SERVICECHARGE_CALCULATIONPHASE_SUBTOTALPHASE = "SUBTOTAL_PHASE";

            /// <summary>
            /// Order line item "Booking Deposit" for deposit amount
            /// </summary>
            public const string Deposit_LineItem = "Booking Deposit";

            /// <summary>
            /// Order line item "Transport Rate" for full amount
            /// </summary>
            public const string TotalCost_LineItem = "Transport Rate";

            /// <summary>
            /// Order line item "Processing Fee" for service charge amount
            /// </summary>
            public const string ProcessingFee_ServiceCharge_LineItem = "Processing Fee";
        }

        public class WebhookEvent
        {
            /// <summary>
            /// Webhook event "payment.updated"
            /// </summary>
            public const string PAYMENT_UPDATED = "payment.updated";

            /// <summary>
            /// Webhook event "refund.updated"
            /// </summary>
            public const string REFUND_UPDATED = "refund.updated";

            /// <summary>
            /// Webhook event "invoice.updated"
            /// </summary>
            public const string INVOICE_UPDATED = "invoice.updated";

            /// <summary>
            /// Webhook event "invoice.canceled"
            /// </summary>
            public const string INVOICE_CANCELED = "invoice.canceled";

            /// <summary>
            /// Webhook event "invoice.deleted"
            /// </summary>
            public const string INVOICE_DELETED = "invoice.deleted";

            /// <summary>
            /// Webhook event "invoice.published"
            /// </summary>
            public const string INVOICE_PUBLISHED = "invoice.published";

            /// <summary>
            /// Webhook event "invoice.refunded"
            /// </summary>
            public const string INVOICE_REFUNDED = "invoice.refunded";
        }

        public class MessageTemplate
        {
            /// <summary>
            /// Message template name "SquarePayment.DepositPaymentDetails"
            /// </summary>
            public const string DepositPaymentDetails = "SquarePayment.DepositPaymentDetails";

            /// <summary>
            /// Message template name "SquarePayment.FullPaymentDetails"
            /// </summary>
            public const string FullPaymentDetails = "SquarePayment.FullPaymentDetails";

            /// <summary>
            /// Message template name "SquarePayment.AdditionalPaymentDetails"
            /// </summary>
            public const string AdditionalPaymentDetails = "SquarePayment.AdditionalPaymentDetails";
        }
    }
}